import type { GanttTask } from "./types"

export const sampleTasks: GanttTask[] = [
  {
    id: "discovery",
    name: "Discovery",
    pic: "Ava Chen",
    start: "2026-08-18",
    end: "2026-09-04",
    color: "sky",
    children: [
      {
        id: "interviews",
        name: "Stakeholder interviews",
        pic: "Ava Chen",
        start: "2026-08-18",
        end: "2026-08-27",
        color: "sky",
      },
      {
        id: "research",
        name: "Competitive review",
        pic: "Noah Patel",
        start: "2026-08-24",
        end: "2026-09-04",
        color: "sky",
      },
    ],
  },
  {
    id: "design",
    name: "Design",
    pic: "Noah Patel",
    start: "2026-09-01",
    end: "2026-09-19",
    color: "violet",
    children: [
      {
        id: "wireframes",
        name: "Wireframes",
        pic: "Noah Patel",
        start: "2026-09-01",
        end: "2026-09-09",
        color: "violet",
      },
      {
        id: "visual",
        name: "Visual polish",
        pic: "Mia Park",
        start: "2026-09-08",
        end: "2026-09-19",
        color: "violet",
      },
    ],
  },
  {
    id: "engineering",
    name: "Engineering",
    pic: "Mia Park",
    start: "2026-09-08",
    end: "2026-10-10",
    color: "emerald",
    children: [
      {
        id: "api",
        name: "API contracts",
        pic: "Jordan Lee",
        start: "2026-09-08",
        end: "2026-09-22",
        color: "emerald",
      },
      {
        id: "web",
        name: "Web app build",
        pic: "Mia Park",
        start: "2026-09-15",
        end: "2026-10-03",
        color: "emerald",
      },
      {
        id: "qa",
        name: "QA & hardening",
        pic: "Sam Ortiz",
        start: "2026-09-28",
        end: "2026-10-10",
        color: "emerald",
      },
    ],
  },
  {
    id: "launch",
    name: "Launch",
    pic: "Jordan Lee",
    start: "2026-10-06",
    end: "2026-10-24",
    color: "amber",
    children: [
      {
        id: "docs",
        name: "Release notes & docs",
        pic: "Ava Chen",
        start: "2026-10-06",
        end: "2026-10-14",
        color: "amber",
      },
      {
        id: "golive",
        name: "Go-live & hypercare",
        pic: "Jordan Lee",
        start: "2026-10-15",
        end: "2026-10-24",
        color: "amber",
      },
    ],
  },
]
